server:
  port: 8070

spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/mybatisdb
        username: root
        password: 940521

mybatis:
  typeAliasesPackage: cn.com.pojo
  mapperLocations: classpath:mappers/*.xml

logging:
  level: 
    cn.com.mapper: debug
